# Standard Config from CLIP Finetuning on CUB

model_architecture: 'ViT-B/32'
batch_size: 64
epochs: 30
lr: 0.00010388222203744893
beta1: 0.9
beta2: 0.98
eps: 0.01
weight_decay: 0.146202428659217
warmup_steps: 5
validation_split: 0.2
n_splits: 1
log_interval: 10
optim: 'AdamW'
mode: 'val' #train or val
scheduler: 'yes'
cuda_det: null #null wird zu None
seed: null #42