method: random
metric:
  name: Val Accuracy
  goal: maximize
parameters:
  model_architecture: 
    value: 'RN50'
  batch_size: 
    values: [16, 32, 64]
  epochs: 
    min: 15
    max: 30
  lr:
    min: 1.e-9
    max: 1.e-4
  beta1: 
    value: 0.9
  beta2: 
    value: 0.999
  eps: 
    values: [0.01, 0.1, 1.e-8]
  weight_decay: 
    min: 0.0001
    max: 0.2
  warmup_steps: 
    min: 1
    max: 15
  validation_split: 
    value: 0.1
  n_splits: 
    value: 1
  seed: 
    value: 42
  log_interval: 
    value: 10
  optim:
    value: 'AdamW'
  mode:
    value: 'train' # 'val'
  scheduler:
    value: 'no' # 'yes'
early_terminate:
  type: hyperband
  min_iter: 3