method: random
metric:
  name: Val Accuracy
  goal: maximize
parameters:
  model_architecture: 
    value: 'ViT-B/32'
  batch_size: 
    values: [16, 32, 64]
  epochs: 
    min: 15
    max: 25
  lr:
    min: 1.e-9
    max: 4.e-4
  beta1: 
    value: 0.9
  beta2: 
    value: 0.98
  eps: 
    value: 0.01
  weight_decay: 
    min: 0.005
    max: 0.3
  warmup_steps: 
    min: 1
    max: 15
  validation_split: 
    value: 0.1
  n_splits: 
    value: 1
  seed: 
    value: 42
  log_interval: 
    value: 10
  optim:
    value: 'AdamW'
  mode:
    values: ['val', 'train']
  scheduler:
    values: ['yes', 'no']
early_terminate:
  type: hyperband
  min_iter: 3